/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author CASA
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    public Principal(JLabel NombreUsuario, JButton btnreservahotel, JButton btnreservavuelo, JMenuItem cerrar, JMenu jMenu1, JMenuBar jMenuBar1, JMenuItem menuactualizar) {
        this.NombreUsuario = NombreUsuario;
        this.btnreservahotel = btnreservahotel;
        this.btnreservavuelo = btnreservavuelo;
        this.cerrar = cerrar;
        this.jMenu1 = jMenu1;
        this.jMenuBar1 = jMenuBar1;
        this.menuactualizar = menuactualizar;
    }

    public JLabel getNombreUsuario() {
        return NombreUsuario;
    }

    public void setNombreUsuario(JLabel NombreUsuario) {
        this.NombreUsuario = NombreUsuario;
    }

    public JButton getBtnpagotargeta() {
        return btnpagotargeta;
    }

    public void setBtnpagotargeta(JButton btnpagotargeta) {
        this.btnpagotargeta = btnpagotargeta;
    }

    public JButton getBtnreservahotel() {
        return btnreservahotel;
    }

    public void setBtnreservahotel(JButton btnreservahotel) {
        this.btnreservahotel = btnreservahotel;
    }

    public JButton getBtnreservavuelo() {
        return btnreservavuelo;
    }

    public void setBtnreservavuelo(JButton btnreservavuelo) {
        this.btnreservavuelo = btnreservavuelo;
    }

    public JMenuItem getCerrar() {
        return cerrar;
    }

    public void setCerrar(JMenuItem cerrar) {
        this.cerrar = cerrar;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenuItem getMenuactualizar() {
        return menuactualizar;
    }

    public void setMenuactualizar(JMenuItem menuactualizar) {
        this.menuactualizar = menuactualizar;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnreservavuelo = new javax.swing.JButton();
        btnpagotargeta = new javax.swing.JButton();
        btnreservahotel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NombreUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuactualizar = new javax.swing.JMenuItem();
        cerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnreservavuelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/avion .png"))); // NOI18N

        btnpagotargeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/tarjeta-bancaria.png"))); // NOI18N

        btnreservahotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/hotel.png"))); // NOI18N

        jLabel1.setText("RESERVA DE VUELOS");

        jLabel2.setText("RESERVA DE HOTELES");

        jLabel3.setText("ACTUALIZAR TARJETA ");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel4.setText("AIR LINE WORLD");

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N
        jLabel5.setText("Bienvenido ");

        NombreUsuario.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/usuario.png"))); // NOI18N

        menuactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/actualizar-flecha.png"))); // NOI18N
        menuactualizar.setText("Actualizar datos");
        jMenu1.add(menuactualizar);

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cerrar-sesion.png"))); // NOI18N
        cerrar.setText("Cerrar Sesion");
        jMenu1.add(cerrar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnreservavuelo)
                            .addComponent(jLabel1))
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnreservahotel)
                            .addComponent(jLabel2))
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnpagotargeta)
                            .addComponent(jLabel3))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(NombreUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnreservahotel)
                    .addComponent(btnreservavuelo)
                    .addComponent(btnpagotargeta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NombreUsuario;
    private javax.swing.JButton btnpagotargeta;
    private javax.swing.JButton btnreservahotel;
    private javax.swing.JButton btnreservavuelo;
    private javax.swing.JMenuItem cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuactualizar;
    // End of variables declaration//GEN-END:variables
}
